# Generated by Django 5.1.1 on 2024-09-04 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_alter_parcel_courier_alter_parcel_delivered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_parcels', to=settings.AUTH_USER_MODEL),
        ),
    ]
