# Generated by Django 5.1.1 on 2024-09-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_alter_parcel_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='customer',
            field=models.BooleanField(default=True),
        ),
    ]
